# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MICROPOSTS_DATABASE_USERNAME'] %>
  password: <%= ENV['MICROPOSTS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  # database: rails-onboarding-app_development
  database: rails-onboarding-app_development

test:
  <<: *default
  database: rails-onboarding-app_test


production:
  <<: *default
  database: rails-onboarding-app_production
  username: ruby-getting-started
  password: <%= ENV['RAILS-ONBOARDING-APP_DATABASE_PASSWORD'] %>
